name: Deploy Flask App to EC2

on:
  push:
    branches: [ main ]  # jab main branch me push hoga tab deploy karega

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H EC2_PUBLIC_IP >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@EC2_PUBLIC_IP "cd /home/ubuntu/GHA-3FA && git pull && sudo systemctl restart flaskapp" 
