name: Deploy to EC2

on:
  push:
    branches:
      - master  # ab master branch pe push hone par trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/my-app  # yahan tera Flask app hona chahiye
            git pull origin master
            pip install -r requirements.txt
            nohup flask run --host=0.0.0.0 --port=80 &
